using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using VRC.SDK3.UdonNetworkCalling;
using UdonSharp;
using VRC.Udon;
using VRC.Udon.Common;
using VRC.Udon.Common.Interfaces;
using VRC.Udon.Editor.ProgramSources;
using VRC.Udon.Editor.ProgramSources.Attributes;
using Magma.VRC.UdonLuau;

[assembly: UdonProgramSourceNewMenu(typeof(LuauProgramAsset), "UdonLuau Program Asset")]

namespace Magma.VRC.UdonLuau
{
    /// <summary>A public function of a script, as listed in the inspector.</summary>
    [Serializable]
    public class LuauMethodInfo
    {
        /// <summary>The function's name, parameters and return types.</summary>
        public string signature;

        /// <summary>The Udon entry point that runs the function.</summary>
        public string entryPoint;

        /// <summary>Whether other clients may run the function over the network.</summary>
        public bool networkCallable;

        /// <summary>The network rate limit in events per second; 0 means the SDK default.</summary>
        public int maxEventsPerSecond;
    }

    /// <summary>An Udon program source compiled from a .lua or .luau script.</summary>
    [CreateAssetMenu(menuName = "VRChat/UdonLuau Program Asset", fileName = "New UdonLuau Program Asset", order = 101)]
    public class LuauProgramAsset : UdonProgramAsset
    {
        private static readonly Type[] FileLogParameters = { typeof(string), typeof(string), typeof(int), typeof(int) };
        private static readonly MethodInfo LogFileError = typeof(Debug).GetMethod("LogPlayerBuildError", BindingFlags.NonPublic | BindingFlags.Static, null, FileLogParameters, null);
        private static readonly MethodInfo LogFileWarning = typeof(Debug).GetMethod("LogCompilerWarning", BindingFlags.NonPublic | BindingFlags.Static, null, FileLogParameters, null);

        [SerializeField] private TextAsset sourceScript;
        [SerializeField] private bool autoGenerated;
        [SerializeField] private List<LuauDiagnostic> diagnostics = new List<LuauDiagnostic>();
        [SerializeField] private List<LuauFieldAnnotations> fieldAnnotations = new List<LuauFieldAnnotations>();
        [SerializeField] private List<LuauScriptReference> scriptReferences = new List<LuauScriptReference>();
        [SerializeField] private List<LuauMethodInfo> methods = new List<LuauMethodInfo>();
        [SerializeField] private BehaviourSyncMode behaviourSyncMode = BehaviourSyncMode.Any;
        [SerializeField] private string interfaceText = "";
        [SerializeField] private string disassembly = "";

        [NonSerialized] private bool _showDisassembly;
        [NonSerialized] private bool _showMethods;
        [NonSerialized] private NetworkCallingEntrypointMetadata[] _networkCallables;
        [NonSerialized] private readonly Dictionary<string, bool> _referenceFoldouts = new Dictionary<string, bool>();

        /// <summary>Whether the asset was created automatically next to its script, so it follows the script's moves and deletion.</summary>
        public bool AutoGenerated
        {
            get => autoGenerated;
            internal set => autoGenerated = value;
        }

        /// <summary>Returns the program asset whose source is the given script, or null.</summary>
        public static LuauProgramAsset ForScript(TextAsset script) => script == null ? null : FindAll().FirstOrDefault(a => a.SourceScript == script);

        /// <summary>The name other scripts use for this program: the source file name without extension.</summary>
        public string ScriptName => ScriptRegistry.ScriptName(sourceScript);

        /// <summary>Whether a program source is the Luau or UdonSharp program of the named script.</summary>
        public static bool IsProgramOf(AbstractUdonProgramSource source, string script) =>
            source is LuauProgramAsset luau ? luau.ScriptName == script : UdonSharpScripts.IsProgramOf(source, script);

        /// <summary>The .lua or .luau script this program is compiled from.</summary>
        public TextAsset SourceScript
        {
            get => sourceScript;
            set => sourceScript = value;
        }

        /// <summary>Messages from the last compilation.</summary>
        public IReadOnlyList<LuauDiagnostic> Diagnostics => diagnostics;

        /// <summary>Whether the last compilation failed.</summary>
        public bool HasErrors => diagnostics.Any(d => !d.isWarning);

        /// <summary>The sync mode the script declares with @syncmode.</summary>
        public BehaviourSyncMode SyncMode => behaviourSyncMode;

        /// <summary>The compiled program, or null.</summary>
        public IUdonProgram Program => program;

        /// <summary>Returns every program asset in the project.</summary>
        public static IEnumerable<LuauProgramAsset> FindAll() =>
            AssetDatabase.FindAssets($"t:{nameof(LuauProgramAsset)}")
                .Select(guid => AssetDatabase.LoadAssetAtPath<LuauProgramAsset>(AssetDatabase.GUIDToAssetPath(guid)))
                .Where(asset => asset != null);

        /// <summary>Applies sync modes to every UdonBehaviour in the open scenes that uses a UdonLuau program.</summary>
        public static void ApplySyncModesInOpenScenes() => SyncModes.Apply(SyncModes.SceneBehaviours());

        /// <inheritdoc />
        protected override void RefreshProgramImpl()
        {
            diagnostics.Clear();
            fieldAnnotations.Clear();
            scriptReferences.Clear();
            _networkCallables = null;
            behaviourSyncMode = BehaviourSyncMode.Any;
            disassembly = "";

            if (sourceScript == null)
            {
                program = null;
                return;
            }

            if (LuauCatalog.Current == null)
            {
                program = null;
                diagnostics.Add(new LuauDiagnostic { line = 1, column = 1, message = "The UdonLuau native compiler is not loaded; see the console for how to fix it." });
                return;
            }

            ScriptRegistry.EnsureCurrent();
            string conflict = ScriptRegistry.Conflict(this);
            if (conflict != null)
            {
                program = null;
                diagnostics.Add(new LuauDiagnostic { line = 1, column = 1, message = conflict });
                LogDiagnostics();
                return;
            }

            LuauCompileResult result = LuauCompiler.Compile(sourceScript.text, ScriptName);
            program = result.Program;
            diagnostics.AddRange(result.Diagnostics);
            LogDiagnostics();
            if (program == null) return;

            Apply(result);
            if (!ScriptRegistry.CompilingAll) ProxyGenerator.Generate(new[] { this });
        }

        private void Apply(LuauCompileResult result)
        {
            fieldAnnotations.AddRange(result.Fields);
            scriptReferences.AddRange(result.ScriptReferences);
            _networkCallables = result.NetworkCallables.Count > 0 ? result.NetworkCallables.ToArray() : null;
            disassembly = result.Disassembly;
            behaviourSyncMode = result.SyncMode;
            LastInterface = result.Interface;
            interfaceText = result.Interface.ToString();

            var rates = result.NetworkRates;
            NetworkRates = rates;
            methods.Clear();
            foreach (ScriptMethod m in result.Interface.Methods)
            {
                rates.TryGetValue(m.EntryPoint, out int rate);
                methods.Add(new LuauMethodInfo
                {
                    signature = $"{m.Name}({string.Join(", ", m.Parameters.Select(p => $"{p.Name}: {DisplayType(p)}"))})" + (m.Returns.Count == 0 ? "" : ": " + string.Join(", ", m.Returns.Select(DisplayType))),
                    entryPoint = m.EntryPoint,
                    networkCallable = m.NetworkCallable,
                    maxEventsPerSecond = m.NetworkCallable ? rate : 0,
                });
            }
        }

        private static string DisplayType(ScriptVariable variable)
        {
            if (!string.IsNullOrEmpty(variable.Script)) return variable.UdonType.EndsWith("Array", StringComparison.Ordinal) ? $"{{{variable.Script}}}" : variable.Script;
            Type type = LuauCatalog.Current?.ResolveType(variable.UdonType);
            if (type == null) return variable.UdonType;
            Type element = type.IsArray ? type.GetElementType() : type;
            string name = element == typeof(float) ? "number" : element == typeof(int) ? "int" : element == typeof(bool) ? "boolean" : element == typeof(string) ? "string" : element == typeof(object) ? "any" : element.Name;
            return type.IsArray ? $"{{{name}}}" : name;
        }

        internal LuauCompileResult CompileForHotReload(string source) => LuauCompiler.Compile(source, ScriptName);

        internal string InterfaceText => interfaceText;

        internal ScriptInterface LastInterface { get; private set; }

        /// <summary>The rate limit of each network-callable entry point from the last compilation in this editor session; 0 means the SDK default.</summary>
        public IReadOnlyDictionary<string, int> NetworkRates { get; private set; }

        /// <summary>The script's public functions.</summary>
        public IReadOnlyList<LuauMethodInfo> Methods => methods;

        /// <inheritdoc />
        protected override NetworkCallingEntrypointMetadata[] GetLastNetworkCallingMetadata() => _networkCallables;

        private void LogDiagnostics()
        {
            string path = AssetDatabase.GetAssetPath(sourceScript);
            foreach (LuauDiagnostic d in diagnostics)
            {
                string text = $"[UdonLuau] {path}({d.line},{d.column}): {(d.isWarning ? "warning" : "error")}: {d.message}";
                MethodInfo log = d.isWarning ? LogFileWarning : LogFileError;
                if (log != null)
                    log.Invoke(null, new object[] { text, path, d.line, d.column });
                else if (d.isWarning)
                    Debug.LogWarning(text, this);
                else
                    Debug.LogError(text, this);
            }
        }

        /// <inheritdoc />
        protected override void DrawProgramSourceGUI(UdonBehaviour udonBehaviour, ref bool dirty)
        {
            if (udonBehaviour == null) DrawSourceField(ref dirty);

            foreach (LuauDiagnostic d in diagnostics)
                EditorGUILayout.HelpBox($"{d.line}:{d.column}: {d.message}", d.isWarning ? MessageType.Warning : MessageType.Error);

            SyncModes.DrawGUI(this, udonBehaviour, ref dirty);

            DrawInteractionArea(udonBehaviour);
            DrawPublicVariables(udonBehaviour, ref dirty);
            DrawMethods();

            if (udonBehaviour != null) return;
            _showDisassembly = EditorGUILayout.Foldout(_showDisassembly, "Compiled Program", true);
            if (!_showDisassembly) return;
            using (new EditorGUI.DisabledScope(true))
                EditorGUILayout.TextArea(disassembly);
            DrawProgramDisassembly();
        }

        internal void DrawProxyGUI(UdonBehaviour backing, ref bool dirty)
        {
            if (program == null && serializedUdonProgramAsset != null) program = serializedUdonProgramAsset.RetrieveProgram();

            foreach (LuauDiagnostic d in diagnostics)
                EditorGUILayout.HelpBox($"{d.line}:{d.column}: {d.message}", d.isWarning ? MessageType.Warning : MessageType.Error);

            SyncModes.DrawGUI(this, backing, ref dirty);
            DrawInteractionArea(backing);
            if (Application.isPlaying) DrawRunningVariables(backing);
            else DrawPublicVariables(backing, ref dirty);
            DrawMethods();
        }

        private void DrawRunningVariables(UdonBehaviour backing)
        {
            EditorGUILayout.LabelField("Public Variables", EditorStyles.boldLabel);
            IUdonSymbolTable symbols = program?.SymbolTable;
            using (new EditorGUI.IndentLevelScope())
            {
                if (symbols == null || symbols.GetExportedSymbols().Length == 0)
                {
                    EditorGUILayout.LabelField("No public variables.");
                    return;
                }

                foreach (string symbol in symbols.GetExportedSymbols())
                {
                    bool changed = false;
                    object value = DrawPublicVariableField(symbol, backing.GetProgramVariable(symbol), symbols.GetSymbolType(symbol), ref changed, true);
                    if (changed) backing.SetProgramVariable(symbol, value);
                }
            }
        }

        private void DrawMethods()
        {
            if (methods.Count == 0) return;
            _showMethods = EditorGUILayout.Foldout(_showMethods, $"Methods ({methods.Count})", true);
            if (!_showMethods) return;

            using (new EditorGUI.IndentLevelScope())
            {
                foreach (LuauMethodInfo method in methods)
                {
                    EditorGUILayout.LabelField(method.signature, EditorStyles.boldLabel);
                    using (new EditorGUI.IndentLevelScope())
                    {
                        EditorGUILayout.LabelField("Entry point", method.entryPoint, EditorStyles.miniLabel);
                        string network = method.networkCallable
                            ? $"Network callable · max {(method.maxEventsPerSecond > 0 ? method.maxEventsPerSecond + "/s" : "SDK default")}"
                            : "Local only";
                        EditorGUILayout.LabelField("Network", network, EditorStyles.miniLabel);
                    }
                }
            }
        }

        private void DrawSourceField(ref bool dirty)
        {
            EditorGUI.BeginChangeCheck();
            var script = (TextAsset)EditorGUILayout.ObjectField("Source Script", sourceScript, typeof(TextAsset), false);
            if (EditorGUI.EndChangeCheck())
            {
                Undo.RecordObject(this, "Change UdonLuau Source");
                sourceScript = script;
                dirty = true;
                RefreshProgram();
            }

            using (new EditorGUI.DisabledScope(sourceScript == null || Application.isPlaying))
            {
                if (GUILayout.Button("Compile")) RefreshProgram();
            }
        }

        /// <inheritdoc />
        protected override object GetPublicVariableDefaultValue(string symbol, Type type)
        {
            if (program?.SymbolTable == null || !program.SymbolTable.TryGetAddressFromSymbol(symbol, out uint address)) return null;
            if (!program.Heap.TryGetHeapVariable(address, out object value) || value is UdonBaseHeapReference) return null;
            return type == null || type.IsInstanceOfType(value) ? value : null;
        }

        /// <inheritdoc />
        protected override object DrawPublicVariableField(string symbol, object variableValue, Type variableType, ref bool dirty, bool enabled)
        {
            List<LuauAnnotation> annotations = fieldAnnotations.FirstOrDefault(f => f.symbol == symbol)?.annotations ?? new List<LuauAnnotation>();
            string script = scriptReferences.FirstOrDefault(r => r.symbol == symbol)?.script;
            if (annotations.Count == 0 && script == null) return base.DrawPublicVariableField(symbol, variableValue, variableType, ref dirty, enabled);
            if (Find(annotations, "hideininspector") != null) return variableValue;

            LuauAnnotation header = Find(annotations, "header");
            if (header != null)
            {
                EditorGUILayout.Space();
                EditorGUILayout.LabelField(Argument(header, 0), EditorStyles.boldLabel);
            }

            LuauAnnotation space = Find(annotations, "space");
            if (space != null) EditorGUILayout.Space(Number(Argument(space, 0), 8f));

            var label = new GUIContent(symbol, Argument(Find(annotations, "tooltip"), 0));
            LuauAnnotation range = Find(annotations, "range");
            LuauAnnotation multiline = Find(annotations, "multiline") ?? Find(annotations, "textarea");

            if (script != null && typeof(UdonBehaviour).IsAssignableFrom(variableType))
                return DrawReference(label, variableValue as UdonBehaviour, script, ref dirty, enabled);
            if (script != null && variableType.IsArray && typeof(Component).IsAssignableFrom(variableType.GetElementType()))
                return DrawReferenceArray(label, symbol, variableValue as Array, variableType.GetElementType(), script, ref dirty, enabled);

            if (range != null && IsSliderType(variableType))
                return DrawSlider(label, variableValue, variableType, Number(Argument(range, 0), 0f), Number(Argument(range, 1), 1f), ref dirty, enabled);
            if (multiline != null && variableType == typeof(string))
                return DrawTextArea(label, variableValue as string, ref dirty, enabled);

            object result = base.DrawPublicVariableField(symbol, variableValue, variableType, ref dirty, enabled);
            if (!string.IsNullOrEmpty(label.tooltip) && Event.current.type == EventType.Repaint)
            {
                Rect row = GUILayoutUtility.GetLastRect();
                GUI.Label(new Rect(row.x, row.y, EditorGUIUtility.labelWidth, EditorGUIUtility.singleLineHeight), new GUIContent("", label.tooltip));
            }
            return result;
        }

        private static UdonBehaviour DrawReference(GUIContent label, UdonBehaviour value, string script, ref bool dirty, bool enabled)
        {
            using (new EditorGUI.DisabledScope(!enabled))
            {
                EditorGUI.BeginChangeCheck();
                var picked = (UdonBehaviour)EditorGUILayout.ObjectField(new GUIContent($"{label.text} ({script})", label.tooltip), value, typeof(UdonBehaviour), true);
                if (EditorGUI.EndChangeCheck())
                {
                    value = Matching(picked, script);
                    dirty = true;
                }
            }

            if (value != null && !IsProgramOf(value.programSource, script))
                EditorGUILayout.HelpBox($"{value.name} does not run {script}.", MessageType.Warning);
            return value;
        }

        private Array DrawReferenceArray(GUIContent label, string symbol, Array value, Type element, string script, ref bool dirty, bool enabled)
        {
            value ??= Array.CreateInstance(element, 0);
            _referenceFoldouts.TryGetValue(symbol, out bool open);
            open = EditorGUILayout.Foldout(open, new GUIContent($"{label.text} ({script}[{value.Length}])", label.tooltip), true);
            _referenceFoldouts[symbol] = open;
            if (!open) return value;

            using (new EditorGUI.DisabledScope(!enabled))
            using (new EditorGUI.IndentLevelScope())
            {
                int size = Math.Max(0, EditorGUILayout.DelayedIntField("Size", value.Length));
                if (size != value.Length)
                {
                    Array resized = Array.CreateInstance(element, size);
                    Array.Copy(value, resized, Math.Min(size, value.Length));
                    value = resized;
                    dirty = true;
                }

                for (int i = 0; i < value.Length; i++)
                {
                    var current = value.GetValue(i) as UdonBehaviour;
                    EditorGUI.BeginChangeCheck();
                    var picked = (UdonBehaviour)EditorGUILayout.ObjectField($"Element {i}", current, typeof(UdonBehaviour), true);
                    if (EditorGUI.EndChangeCheck())
                    {
                        picked = Matching(picked, script);
                        if (picked == null || element.IsInstanceOfType(picked)) value.SetValue(picked, i);
                        dirty = true;
                    }
                    if (current != null && !IsProgramOf(current.programSource, script))
                        EditorGUILayout.HelpBox($"{current.name} does not run {script}.", MessageType.Warning);
                }
            }
            return value;
        }

        private static UdonBehaviour Matching(UdonBehaviour picked, string script)
        {
            if (picked == null || IsProgramOf(picked.programSource, script)) return picked;
            return picked.GetComponents<UdonBehaviour>().FirstOrDefault(b => IsProgramOf(b.programSource, script)) ?? picked;
        }

        private static bool IsSliderType(Type type) => type == typeof(float) || type == typeof(double) || type == typeof(int);

        private static object DrawSlider(GUIContent label, object value, Type type, float min, float max, ref bool dirty, bool enabled)
        {
            using (new EditorGUI.DisabledScope(!enabled))
            {
                EditorGUI.BeginChangeCheck();
                object result;
                if (type == typeof(int))
                    result = EditorGUILayout.IntSlider(label, value is int i ? i : 0, (int)min, (int)max);
                else if (type == typeof(double))
                    result = (double)EditorGUILayout.Slider(label, value is double d ? (float)d : 0f, min, max);
                else
                    result = EditorGUILayout.Slider(label, value is float f ? f : 0f, min, max);
                if (EditorGUI.EndChangeCheck()) dirty = true;
                return result;
            }
        }

        private static object DrawTextArea(GUIContent label, string value, ref bool dirty, bool enabled)
        {
            using (new EditorGUI.DisabledScope(!enabled))
            {
                EditorGUILayout.LabelField(label);
                EditorGUI.BeginChangeCheck();
                var style = new GUIStyle(EditorStyles.textArea) { wordWrap = true };
                string result = EditorGUILayout.TextArea(value ?? "", style, GUILayout.MinHeight(EditorGUIUtility.singleLineHeight * 3));
                if (EditorGUI.EndChangeCheck()) dirty = true;
                return result;
            }
        }

        private static LuauAnnotation Find(List<LuauAnnotation> annotations, string name) =>
            annotations.LastOrDefault(a => string.Equals(a.name, name, StringComparison.OrdinalIgnoreCase));

        private static string Argument(LuauAnnotation annotation, int index) =>
            annotation?.arguments != null && index < annotation.arguments.Length ? annotation.arguments[index] : null;

        private static float Number(string text, float fallback) =>
            float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out float value) ? value : fallback;
    }
}
