using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using VRC.SDKBase.Editor.BuildPipeline;
using VRC.Udon.Editor.ProgramSources;

namespace Magma.VRC.UdonLuau
{
    [CustomEditor(typeof(LuauProgramAsset))]
    internal sealed class LuauProgramAssetEditor : UdonProgramAssetEditor
    {
    }

    /// <summary>Keeps program assets next to their scripts and compiles UdonLuau programs when scripts change, after domain reloads and on request.</summary>
    [InitializeOnLoad]
    public sealed class LuauEditorHooks : AssetPostprocessor
    {
        private const string Template =
            "-- @range(0, 360)\n" +
            "export local speed: number = 45\n" +
            "\n" +
            "function Start()\n" +
            "    print(`{gameObject.name} started`)\n" +
            "end\n" +
            "\n" +
            "function Update()\n" +
            "    transform:Rotate(Vector3.up, speed * Time.deltaTime)\n" +
            "end\n";

        static LuauEditorHooks()
        {
            EditorApplication.delayCall += () =>
            {
                if (EditorApplication.isPlayingOrWillChangePlaymode) return;
                LuauSettings.ApplyLuaImporterOverrides();
                CompileAll();
            };
        }

        /// <summary>Compiles every UdonLuau program in the project.</summary>
        /// <returns>Whether all of them compiled.</returns>
        public static bool CompileAll()
        {
            bool succeeded = true;
            var assets = LuauProgramAsset.FindAll().Where(a => a.SourceScript != null).ToList();
            ScriptRegistry.CompilingAll = true;
            try
            {
                ScriptRegistry.Batch(() =>
                {
                    ScriptRegistry.EnsureCurrent();
                    foreach (LuauProgramAsset asset in assets)
                    {
                        asset.RefreshProgram();
                        succeeded &= !asset.HasErrors;
                    }
                });
            }
            finally
            {
                ScriptRegistry.CompilingAll = false;
            }

            ProxyGenerator.Generate(assets);
            ProxyGenerator.Prune();
            ProxyLinker.SanitizeOpenScenes();
            LuauProgramAsset.ApplySyncModesInOpenScenes();
            return succeeded;
        }

        /// <summary>Returns the program asset of a script, creating one next to it when none exists.</summary>
        public static LuauProgramAsset EnsureProgramAsset(TextAsset script)
        {
            LuauProgramAsset existing = LuauProgramAsset.ForScript(script);
            if (existing != null || script == null) return existing;

            string scriptPath = AssetDatabase.GetAssetPath(script);
            var asset = ScriptableObject.CreateInstance<LuauProgramAsset>();
            asset.SourceScript = script;
            asset.AutoGenerated = true;
            AssetDatabase.CreateAsset(asset, AssetDatabase.GenerateUniqueAssetPath(GeneratedPath(scriptPath)));
            asset.RefreshProgram();
            AssetDatabase.SaveAssets();
            return asset;
        }

        private static string GeneratedPath(string scriptPath) => Path.ChangeExtension(scriptPath, ".asset").Replace('\\', '/');

        private static string StaticsPath(string scriptPath) => Path.ChangeExtension(scriptPath, ".Static.asset").Replace('\\', '/');

        /// <summary>Creates, refreshes or removes the companion asset holding a script's statics, so it exists exactly when the script declares statics.</summary>
        internal static void SyncStatics(LuauProgramAsset main, bool hasStatics)
        {
            TextAsset script = main.SourceScript;
            if (script == null) return;
            LuauProgramAsset existing = LuauProgramAsset.StaticsForScript(script);
            if (!hasStatics)
            {
                if (existing != null && existing.AutoGenerated) AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(existing));
                return;
            }
            if (existing != null)
            {
                if (!ScriptRegistry.CompilingAll) existing.RefreshProgram();
                return;
            }
            var asset = ScriptableObject.CreateInstance<LuauProgramAsset>();
            asset.SourceScript = script;
            asset.StaticPart = true;
            asset.AutoGenerated = true;
            AssetDatabase.CreateAsset(asset, AssetDatabase.GenerateUniqueAssetPath(StaticsPath(AssetDatabase.GetAssetPath(script))));
            asset.RefreshProgram();
        }

        private static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
        {
            LuauSettings.ApplyLuaImporterOverrides(imported);

            var changed = new HashSet<string>(imported.Where(LuauSettings.IsScriptPath), StringComparer.OrdinalIgnoreCase);
            var deletedScripts = deleted.Where(LuauSettings.IsScriptPath).ToList();
            var moves = moved.Select((to, i) => (from: movedFrom[i], to)).Where(m => LuauSettings.IsScriptPath(m.to) || LuauSettings.IsScriptPath(m.from)).ToList();
            if (changed.Count == 0 && deletedScripts.Count == 0 && moves.Count == 0)
            {
                if (imported.Any(IsUdonSharpProgram)) QueueRegistryRefresh();
                return;
            }

            EditorApplication.delayCall += () =>
            {
                if (EditorApplication.isPlayingOrWillChangePlaymode) return;
                bool structural = deletedScripts.Count > 0 || moves.Count > 0;

                foreach (string path in deletedScripts)
                {
                    foreach (string generatedPath in new[] { GeneratedPath(path), StaticsPath(path) })
                    {
                        var generated = AssetDatabase.LoadAssetAtPath<LuauProgramAsset>(generatedPath);
                        if (generated != null && generated.AutoGenerated && generated.SourceScript == null) AssetDatabase.DeleteAsset(generatedPath);
                    }
                }
                if (deletedScripts.Count > 0) EditorApplication.delayCall += ProxyGenerator.Prune;

                foreach (var (from, to) in moves)
                {
                    var script = AssetDatabase.LoadAssetAtPath<TextAsset>(to);
                    LuauProgramAsset statics = LuauProgramAsset.StaticsForScript(script);
                    if (statics != null && statics.AutoGenerated && AssetDatabase.GetAssetPath(statics) == StaticsPath(from) && AssetDatabase.LoadMainAssetAtPath(StaticsPath(to)) == null)
                        AssetDatabase.MoveAsset(StaticsPath(from), StaticsPath(to));
                    LuauProgramAsset asset = LuauProgramAsset.ForScript(script);
                    if (asset == null || !asset.AutoGenerated || AssetDatabase.GetAssetPath(asset) != GeneratedPath(from)) continue;
                    if (AssetDatabase.LoadMainAssetAtPath(GeneratedPath(to)) == null) AssetDatabase.MoveAsset(GeneratedPath(from), GeneratedPath(to));
                }

                foreach (string path in changed.Concat(moves.Select(m => m.to)).Where(LuauSettings.IsScriptPath))
                {
                    var script = AssetDatabase.LoadAssetAtPath<TextAsset>(path);
                    if (script != null && LuauProgramAsset.ForScript(script) == null)
                    {
                        EnsureProgramAsset(script);
                        structural = true;
                    }
                }

                if (structural)
                {
                    CompileAll();
                    return;
                }

                ScriptRegistry.Batch(() =>
                {
                    ScriptRegistry.EnsureCurrent();
                    foreach (LuauProgramAsset asset in LuauProgramAsset.FindAll())
                        if (asset.SourceScript != null && changed.Contains(AssetDatabase.GetAssetPath(asset.SourceScript))) asset.RefreshProgram();
                });
                LuauProgramAsset.ApplySyncModesInOpenScenes();
            };
            EditorApplication.QueuePlayerLoopUpdate();
        }

        private static bool _registryRefreshQueued;

        private static void QueueRegistryRefresh()
        {
            if (_registryRefreshQueued) return;
            _registryRefreshQueued = true;
            EditorApplication.delayCall += () =>
            {
                _registryRefreshQueued = false;
                if (!EditorApplication.isPlayingOrWillChangePlaymode) ScriptRegistry.Refresh();
            };
            EditorApplication.QueuePlayerLoopUpdate();
        }

        private static bool IsUdonSharpProgram(string path)
        {
            if (!path.StartsWith("Assets/SerializedUdonPrograms/", StringComparison.Ordinal)) return false;
            string source = AssetDatabase.GUIDToAssetPath(Path.GetFileNameWithoutExtension(path));
            return !string.IsNullOrEmpty(source) && AssetDatabase.GetMainAssetTypeAtPath(source) == typeof(UdonSharp.UdonSharpProgramAsset);
        }

        [MenuItem("Assets/Create/VRChat/UdonLuau Script", false, 100)]
        private static void CreateScript()
        {
            string extension = LuauSettings.instance.TreatLuaAsLuau ? "lua" : "luau";
            ProjectWindowUtil.CreateAssetWithContent($"NewLuauScript.{extension}", Template);
        }

        [MenuItem("Tools/UdonLuau/Compile All Scripts", false, 0)]
        private static void CompileAllMenu()
        {
            if (CompileAll()) Debug.Log("[UdonLuau] All scripts compiled.");
            else Debug.LogError("[UdonLuau] Some UdonLuau scripts failed to compile; see the errors above.");
        }
    }

    internal sealed class LuauDeleteWatcher : AssetModificationProcessor
    {
        private static AssetDeleteResult OnWillDeleteAsset(string path, RemoveAssetOptions options)
        {
            try
            {
                var scripts = new List<string>();
                var classes = new List<string>();
                if (AssetDatabase.IsValidFolder(path))
                {
                    foreach (string file in Directory.GetFiles(path, "*", SearchOption.AllDirectories))
                        Collect(file.Replace('\\', '/'), scripts, classes);
                }
                else
                {
                    Collect(path, scripts, classes);
                }

                if (scripts.Count > 0 || classes.Count > 0) ProxyGenerator.DeleteFor(scripts, classes);
            }
            catch (IOException)
            {
            }
            return AssetDeleteResult.DidNotDelete;
        }

        private static void Collect(string path, List<string> scripts, List<string> classes)
        {
            if (LuauSettings.IsScriptPath(path))
            {
                string guid = AssetDatabase.AssetPathToGUID(path);
                if (!string.IsNullOrEmpty(guid)) scripts.Add(guid);
            }
            else if (path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) && !path.StartsWith(ProxyGenerator.Folder + "/", StringComparison.Ordinal))
            {
                Type type = AssetDatabase.LoadAssetAtPath<MonoScript>(path)?.GetClass();
                if (type != null && typeof(UdonSharp.UdonSharpBehaviour).IsAssignableFrom(type)) classes.Add(type.FullName);
            }
        }
    }

    internal sealed class LuauBuildCompile : IVRCSDKBuildRequestedCallback
    {
        public int callbackOrder => 99;

        public bool OnBuildRequested(VRCSDKRequestedBuildType requestedBuildType)
        {
            if (requestedBuildType == VRCSDKRequestedBuildType.Avatar) return true;
            if (LuauEditorHooks.CompileAll())
            {
                AssetDatabase.SaveAssets();
                return true;
            }

            Debug.LogError("[UdonLuau] Some UdonLuau scripts failed to compile; fix the errors above before building.");
            return false;
        }
    }
}
